/* src/gen_blobs.c — generates embedded_blobs.{c,h} from input files.
 *
 * Usage: gen_blobs <out.c> <out.h> <sym1> <file1> [<sym2> <file2> ...]
 *
 * Emits each file as a C byte array plus a length. Output is plain
 * portable C — no compiler extensions needed.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static long emit_array(FILE *out, const char *sym, const char *path)
{
    FILE *in = fopen(path, "rb");
    if (!in) { fprintf(stderr, "gen_blobs: cannot open %s\n", path); exit(1); }

    fprintf(out, "const unsigned char %s[] = {", sym);
    int c, i = 0;
    long n = 0;
    while ((c = fgetc(in)) != EOF) {
        if ((i++ % 16) == 0) fputs("\n    ", out);
        fprintf(out, "0x%02x,", (unsigned)c);
        n++;
    }
    fputs("\n};\n", out);
    fprintf(out, "const unsigned long %s_len = %ldUL;\n\n", sym, n);
    fclose(in);
    return n;
}

int main(int argc, char **argv)
{
    if (argc < 5 || (argc % 2) != 1) {
        fprintf(stderr,
                "usage: gen_blobs <out.c> <out.h> <sym1> <file1> "
                "[<sym2> <file2> ...]\n");
        return 1;
    }

    FILE *c = fopen(argv[1], "w");
    FILE *h = fopen(argv[2], "w");
    if (!c || !h) { perror("open"); return 1; }

    fputs("/* Auto-generated by gen_blobs — do not edit. */\n",  c);
    fputs("/* Auto-generated by gen_blobs — do not edit. */\n",  h);
    fputs("#ifndef CFETCH_EMBEDDED_BLOBS_H\n",                   h);
    fputs("#define CFETCH_EMBEDDED_BLOBS_H\n\n",                 h);

    for (int i = 3; i < argc; i += 2) {
        const char *sym  = argv[i];
        const char *path = argv[i + 1];
        emit_array(c, sym, path);
        fprintf(h, "extern const unsigned char %s[];\n",     sym);
        fprintf(h, "extern const unsigned long %s_len;\n\n", sym);
        fprintf(stderr, "gen_blobs: embedded %s (%s)\n", sym, path);
    }

    fputs("#endif\n", h);
    fclose(c); fclose(h);
    return 0;
}
